package unit.swingy.view.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import lombok.Getter;
import unit.swingy.model.characters.DataBase;
import unit.swingy.model.characters.Hero;
import unit.swingy.model.characters.HeroBuilder;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;

@Getter
public class ChooseHeroGui {

	private Hero hero;
	private ArrayList<Hero> heroesList;

	private JTable Table;
	private JButton Play;
	private JButton AddHero;
	private JButton DeleteHero;
	private JPanel Panel;

	public ChooseHeroGui() {
		hero = null;

	}


	public Hero chooseHero(DataBase db, HeroBuilder builder) {

		System.out.println(">> Starting GUI ChooseHero method...");

		createUIComponents();

		//init frame
		JFrame frame = new JFrame("JFrame Title");
		frame.setContentPane(new ChooseHeroGui().getPanel());
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);

//		String[] columns = db.getColumnNames();
//		Object[][] data = {
//				{1, "Ramesh Raman", "reg", 5, 5, 5, 5, 5, 6, 6, 6}
//		};


//		heroesList = db.getHeroesList(builder);
//		Table.setModel(new DefaultTableModel());


		return hero;
	}


	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		Panel = new JPanel();
		Panel.setLayout(new GridLayoutManager(3, 4, new Insets(0, 0, 0, 0), -1, -1));
		final Spacer spacer1 = new Spacer();
		Panel.add(spacer1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
		Play = new JButton();
		Play.setText("Play");
		Panel.add(Play, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		AddHero = new JButton();
		AddHero.setText("+");
		Panel.add(AddHero, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		DeleteHero = new JButton();
		DeleteHero.setText("-");
		Panel.add(DeleteHero, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JScrollPane scrollPane1 = new JScrollPane();
		Panel.add(scrollPane1, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		scrollPane1.setViewportView(Table);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return Panel;
	}

	private void createUIComponents() {
		// TODO: place custom component creation code here
		createTable();

	}

	private void createTable() {
		String[] columns = {"Whois", "who"};
		Object[][] data = {
				{"Putin", "hooylo"},
				{"Katzapy", "pidary"}
		};
		Table = new JTable(data, columns);
		Table.setFillsViewportHeight(true);
	}
}
