package unit.swingy.view.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import lombok.Getter;
import unit.swingy.model.characters.DataBase;
import unit.swingy.model.characters.Hero;
import unit.swingy.model.characters.HeroBuilder;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import java.awt.*;
import java.util.ArrayList;

@Getter
public class ChooseHeroGui {

	private DataBase db = DataBase.getInstance();
	private HeroBuilder hb = new HeroBuilder();

	private Hero hero = null;
	private ArrayList<Hero> heroesList;

	private JTable table;
	private JButton play;
	private JButton addHero;
	private JButton deleteHero;
	private JPanel mainPanel;
	private JTextPane textPane;
	private JScrollPane paneLeft;
	private JScrollPane paneRight;

	public ChooseHeroGui() {
		$$$setupUI$$$();
		table.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent event) {
				hero = heroesList.get(table.getSelectedRow());
				displayHeroStats();
			}
		});

	}

	public Hero chooseHero() {

		System.out.println(">> Starting GUI ChooseHero method...");


		//init frame
		JFrame frame = new JFrame("Choose your hero");
		frame.setContentPane(this.getMainPanel());
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);


		return hero;
	}

	private void createTable() {

		heroesList = db.getHeroesList(hb);
		int rows = heroesList.size();

		String[] columns = {"NAME", "CLASS", "LEVEL", "EXP"};
		Object[][] data = new Object[rows][4];

		for (int r = 0; r < rows; r++) {
			data[r][0] = heroesList.get(r).getName();
			data[r][1] = heroesList.get(r).getClas();
			data[r][2] = heroesList.get(r).getLevel();
			data[r][3] = heroesList.get(r).getExp();
		}

		table = new JTable(data, columns);
		table.setFillsViewportHeight(true);

	}

	private void displayHeroStats() {

		textPane.setText("");
		SimpleAttributeSet atr = new SimpleAttributeSet();
		Document doc = textPane.getStyledDocument();

		try {
			doc.insertString(doc.getLength(), "Name: " + hero.getName() + "\n", atr);
			doc.insertString(doc.getLength(), "Class: " + hero.getClas() + "\n\n", atr);
			doc.insertString(doc.getLength(), "Level: " + hero.getLevel() + "\n", atr);
			doc.insertString(doc.getLength(), "Exp: " + hero.getExp() + "\n\n", atr);
			doc.insertString(doc.getLength(), "HP: " + hero.getHp() + "\n", atr);
			doc.insertString(doc.getLength(), "Attack: " + hero.getAttack() + "\n", atr);
			doc.insertString(doc.getLength(), "Defence: " + hero.getDefence() + "\n\n", atr);
			doc.insertString(doc.getLength(), "Weapon: " + hero.getWeapon() + "\n", atr);
			doc.insertString(doc.getLength(), "Armor: " + hero.getArmor() + "\n", atr);
			doc.insertString(doc.getLength(), "Helm: " + hero.getHelm() + "\n", atr);
		} catch (BadLocationException e) {
			e.printStackTrace();
		}
	}


	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		mainPanel = new JPanel();
		mainPanel.setLayout(new GridLayoutManager(2, 4, new Insets(0, 0, 0, 0), -1, -1));
		paneLeft = new JScrollPane();
		mainPanel.add(paneLeft, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		paneLeft.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
		paneLeft.setViewportView(table);
		paneRight = new JScrollPane();
		mainPanel.add(paneRight, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(200, -1), null, 0, false));
		paneRight.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
		textPane = new JTextPane();
		textPane.setEditable(false);
		textPane.setText("Select a hero");
		paneRight.setViewportView(textPane);
		play = new JButton();
		play.setText("Play");
		mainPanel.add(play, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer1 = new Spacer();
		mainPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
		deleteHero = new JButton();
		deleteHero.setText("-");
		mainPanel.add(deleteHero, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(27, 30), null, 0, false));
		addHero = new JButton();
		addHero.setText("+");
		mainPanel.add(addHero, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return mainPanel;
	}

	private void createUIComponents() {
		// TODO: place custom component creation code here
		createTable();

	}


}
